project:
  type: website
  resources:
   - assets/*

website:
  title: "Open Science Workflow Training for ISC"
  reader-mode: true
  site-url: "https://moshima-pifsc.github.io/2025-01-ISC-OpenScienceTraining" 
  repo-url: "https://github.com/MOshima-PIFSC/2025-01-ISC-OpenScienceTraining"
  repo-actions: [source, issue]
  search: true
  back-to-top-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/MOshima-PIFSC/2025-01-ISC-OpenScienceTraining
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Day 1"
        href: assets/day-1.html
        contents:
        - text: "Welcome"
          file: assets/day-1-welcome.qmd
        - text: "GitHub for Collaborative Workflows"
          file: assets/day-1-pres-github_basics.qmd
        - text: "Codespaces and VS Code"
          file: assets/day-1-pres-codespaces.qmd
        - text: "Reproducible R Environments"
          file: assets/day-1-pres-reproducible_environments.qmd
      - section: "Day 2"
        href: assets/day-2.html
        contents:
        - text: "Script Based Workflows"
          file: assets/day-1-pres-modify-stock-synthesis.qmd
        - text: "Building a Shiny App"
          file: assets/day-2-pres-build-shiny.qmd
      - section: "Day 3"
        href: assets/day-3.html
        contents:
        - text: "Quarto: Reports and presentations"
          file: assets/day-3-pres-quarto.qmd
        - text: "Quarto: Website"
          file: assets/day-4-pres-quarto-website.qmd
        - text: "GitHub pages"
          file: assets/day-4-gh-pages.qmd
      - section: "Example html pages"
        contents: 
        - text: "Works_YS"
          file: 'assets/YS-in-class.qmd'
      - section: "References"  
        contents: 
        - text: "Cheatsheet"
          file: assets/ref-Open_Science_Cheat_Sheet.qmd
        - text: "Helpful Links"  
          file: assets/resources.qmd
      - section: "Contact us"
        contents:
        - text: "Nicholas Ducharme-Barth"
          file: assets/web-about-nd.qmd
        - text: "Megumi Oshima"
          file: assets/web-about-mo.qmd
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/MOshima-PIFSC/2025-01-ISC-OpenScienceTraining/issues/new/choose

format: 
  html:
    toc: true
    toc-expand: false
    theme:
      - default
      - assets/customizations/website-custom.scss
